version: '3'

services:
    auth:
        build: ./auth
        image: auth:latest
        env_file: ./auth/postgres.env
        depends_on:
            - auth-db
        ports:
            - 5000:5000
    auth-db:
        image: postgres:latest
        env_file: ./auth/postgres.env
    nginx:
        build: ./nginx
        image: nginx:latest
        ports:
           - 80:80
        depends_on:
            - auth
            - client
    client:
        build: ./client
        image: client:latest
        ports:
            - 3000:3000
        environment:
            - NODE_ENV=development
            - REACT_APP_SERVICE_URL=http://localhost:80
            - CHOKIDAR_USEPOLLING=true
        depends_on:
            - auth
    playmaster:
        build: ./playmaster
        image: playmaster:latest
        env_file: ./playmaster/redis.env
        ports:
            - 5001:5001
        depends_on:
            - playmaster-db
    playmaster-db:
        image: redis:latest
        env_file: ./playmaster/redis.env
    gamemaster:
        build: ./gamemaster
        image: gamemaster:latest
        env_file: ./gamemaster/postgres2.env
        depends_on:
            - gamemaster-db
        ports:
            - 5002:5002
    gamemaster-db:
        image: postgres:latest
        env_file: ./gamemaster/postgres2.env