version: '3'

services:
    auth:
        build: ./auth
        image: auth:latest
        env_file: ./auth/postgres.env
        depends_on: 
            - auth-db
        ports: 
            - 5000:5000
    auth-db:
        image: postgres:latest
        env_file: ./auth/postgres.env